### ISSUE TITLE
building for windows?

### ISSUE THREAD

**Issue by FocuzJS** [calccrypto/OpenPGP#46]
I'd like to try and use this in my visual c++ project in vs 2017, but all my attempts at building with things like MinGW have been no good. Any advice?

**Comment by calccrypto** [comment]
I'm afraid I haven't been able to get VS or MinGW to work for anything for at least a few years. The closest I've been able to get to building OpenPGP on Windows is with cygwin, which fails because file descriptors were removed from cygwin, and GoogleTest uses file descriptors (it might build if GoogleTest and the tests were removed).

Maybe you can post the error messages you are getting, and we can try to figure it out?
